apiVersion: v1
kind: Service
metadata:
  name: orderiq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orderiq
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
